if(CMAKE_HOST_APPLE)
  # NOTE: See https://gitlab.kitware.com/cmake/cmake/-/blob/master/Modules/FindOpenMP.cmake
  message("Lookup OpenMP in macOS platform...")
  list(APPEND CMAKE_C_IMPLICIT_LINK_DIRECTORIES "/opt/local/lib/libomp")
  list(APPEND CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES "/opt/local/lib/libomp")
  message("CMAKE_C_IMPLICIT_LINK_DIRECTORIES = ${CMAKE_C_IMPLICIT_LINK_DIRECTORIES}")
  message("CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES = ${CMAKE_CXX_IMPLICIT_LINK_DIRECTORIES}")
  set(OpenMP_C_INCLUDE_DIR "/opt/local/include/libomp")
  set(OpenMP_C_FLAG "-Xpreprocessor -fopenmp")
  set(OpenMP_CXX_INCLUDE_DIR "/opt/local/include/libomp")
  set(OpenMP_CXX_FLAG "-Xpreprocessor -fopenmp")
endif()
find_package(OpenMP)
message("OpenMP_libomp_LIBRARY = ${OpenMP_libomp_LIBRARY}")
message("OpenMP_CXX_FLAGS = ${OpenMP_CXX_FLAGS}")
message("OpenMP_CXX_INCLUDE_DIRS = ${OpenMP_CXX_INCLUDE_DIRS}")
message("OpenMP_CXX_LIB_NAMES = ${OpenMP_CXX_LIB_NAMES}")
# if(CMAKE_HOST_APPLE)
#   if(OpenMP_FOUND)
#     # TODO: should change variables? try to use "target" framework of CMake.
#     message("Modify C and CXX compilers flags for OpenMP...")
#     set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
#     set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
#     set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L${OpenMP_omp_LIBRARY}")
#   else()
#     message(WARNING "Not found OpenMP")
#   endif()
# endif()
