if(CMAKE_HOST_APPLE)
  message("Lookup OpenMP in macOS platform...")
  set(OpenMP_PREFIX "/opt/local")
  message("The location prefix of libomp is: ${OpenMP_PREFIX}")
  set(OpenMP_omp_INCLUDE "${OpenMP_PREFIX}/include/libomp")
  set(OpenMP_omp_LIBRARY "${OpenMP_PREFIX}/lib/libomp")
  set(OpenMP_C_LIB_NAMES "omp")
  set(OpenMP_C_FLAGS "-fopenmp -Wno-unused-command-line-argument -I${OpenMP_omp_INCLUDE}" CACHE STRING "" FORCE)
  set(OpenMP_CXX_LIB_NAMES "omp")
  set(OpenMP_CXX_FLAGS "-Xpreprocessor -fopenmp -Wno-unused-command-line-argument -I${OpenMP_omp_INCLUDE}" CACHE STRING "" FORCE)
endif()
find_package(OpenMP)
if(OpenMP_FOUND)
  # TODO: should change variables?
  message("Modify C and CXX compilers flags for OpenMP...")
  set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} ${OpenMP_C_FLAGS}")
  set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} ${OpenMP_CXX_FLAGS}")
  set(CMAKE_EXE_LINKER_FLAGS "${CMAKE_EXE_LINKER_FLAGS} -L${OpenMP_omp_LIBRARY}")
else()
  message(WARNING "Not found OpenMP")
endif()